version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: reto_practicas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./reto-practicas-backend
    restart: always
    environment:
      DB_NAME: reto_practicas
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
